on: [push]

jobs:
  checkstyle:
    name: Run checkstyle on plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npx lix download
      - run: npx lix install haxelib:checkstyle
      - run: npm ci
      - run: npm run ci-checkstyle