on: [push]

jobs:
  checkstyle:
    name: Run checkstyle on plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: lix-pm/setup-lix@1.0.0
        with:
          node-version: 12
      - run: lix download
      - run: lix install haxelib:checkstyle
      - run: npm ci
      - run: npm run ci-checkstyle